name: Issue action
author: Jordan  
description: Descricao da minha action para abrir issue
inputs:
  token:
    description: 'GITHUB TOKEN'
    required: true
  title:
    description: 'Issue title'
    required: true    
  body:
    description: 'Issue body'
    required: true      
  assignees:
    description: 'Issue body assignees'
outputs:
  issue:
    description: 'The issue object as json string'
runs:
  using: 'node12'
  main: 'dist/index.js'