name: CI
on: 
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NODE 
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install --save-dev --save-exact prettier
      - run: npm run format:write
      - run: npm run format:check
      - run: npm test -- --coverage
        env: 
          CI: true